"""cria tabela de manutencoes

Revision ID: 71907d97acf0
Revises: d1ebfc59942d
Create Date: 2026-09-10 10:38:10.463593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71907d97acf0'
down_revision: Union[str, Sequence[str], None] = 'd1ebfc59942d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('building', sa.String(length=150), nullable=True),
    sa.Column('block', sa.String(length=50), nullable=True),
    sa.Column('apartment', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='maintenance_priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING', 'COMPLETED', name='maintenance_status'), nullable=False),
    sa.Column('provider_type', sa.Enum('PERSON', 'COMPANY', name='provider_type'), nullable=True),
    sa.Column('provider_name', sa.String(length=150), nullable=True),
    sa.Column('provider_phone', sa.String(length=30), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenances_id'), 'maintenances', ['id'], unique=False)
    op.create_index(op.f('ix_maintenances_scheduled_date'), 'maintenances', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenances_user_id'), 'maintenances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenances_user_id'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_scheduled_date'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_id'), table_name='maintenances')
    op.drop_table('maintenances')
    # ### end Alembic commands ###
